// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

// Code generated by `make model`. DO NOT EDIT.

package model

// This file contains generated code based on the model.Channel struct.

// -------------------- Property Getters ------------------------ //

// Id gets the Id property of the Channel
func (c *Channel) Id() string {
	return c.id
}

// Name gets the Name property of the Channel
func (c *Channel) Name() string {
	return c.name
}

// CreateAt gets the CreateAt property of the Channel
func (c *Channel) CreateAt() int64 {
	return c.createAt
}

// -------------------- Initializer -------------------- //

// ChannelInitializer provides a container struct to initialize a new Channel object.
type ChannelInitializer struct {
    Id string `json:"id"`
    Name string `json:"name"`
    CreateAt int64 `json:"create_at"`
    
}

// NewChannel creates a new instance of Channel populated with the values from a
// ChannelInitializer instance.
func NewChannel(c *ChannelInitializer) *Channel {
    return &Channel {
        id: c.Id,
        name: c.Name,
        createAt: c.CreateAt,
        
    }
}

// -------------------- JSON Processing Functions -------------------- //

func (c *Channel) UnmarshalJSON(b []byte) (error) {
    var data *ChannelInitializer
    err := json.Unmarshal(b, data)
    if err != nil {
        return nil, err
    }
    *c = *NewChannel(data)
    return nil
}

func (c *Channel) MarshalJSON() ([]byte, error) {
    return json.Marshall(&ChannelInitializer{
        Id: c.id,
        Name: c.name,
        CreateAt: c.createAt,
        
    })
}