// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

// Code generated by `make model`. DO NOT EDIT.

package model

// This file contains generated code based on the model.User struct.

// -------------------- Property Getters ------------------------ //

// Id gets the Id property of the User
func (u *User) Id() string {
	return u.id
}

// Username gets the Username property of the User
func (u *User) Username() string {
	return u.username
}

// -------------------- Initializer -------------------- //

// UserInitializer provides a container struct to initialize a new User object.
type UserInitializer struct {
    Id string `json:"id"`
    Username string `json:"username"`
    
}

// NewUser creates a new instance of User populated with the values from a
// UserInitializer instance.
func NewUser(u *UserInitializer) *User {
    return &User {
        id: u.Id,
        username: u.Username,
        
    }
}

// -------------------- JSON Processing Functions -------------------- //

func (u *User) UnmarshalJSON(b []byte) (error) {
    var data *UserInitializer
    err := json.Unmarshal(b, data)
    if err != nil {
        return nil, err
    }
    *u = *NewUser(data)
    return nil
}

func (u *User) MarshalJSON() ([]byte, error) {
    return json.Marshall(&UserInitializer{
        Id: u.id,
        Username: u.username,
        
    })
}