// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

// Code generated by `make model`. DO NOT EDIT.

package model

// -------------------- Property Getters ------------------------ //

// Id gets the Id property of the Channel
func (c *model.Channel) Id() string {
	return c.id
}
// Name gets the Name property of the Channel
func (c *model.Channel) Name() string {
	return c.name
}
// CreateAt gets the CreateAt property of the Channel
func (c *model.Channel) CreateAt() int64 {
	return c.createAt
}
