// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

// Code generated by `make model`. DO NOT EDIT.
// This file contains generated code based on the model.Channel struct.

package client

type Channel struct {
	Id       string `json:"id"`
	Name     string `json:"name"`
	CreateAt int64  `json:"create_at"`
}
