// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

// Code generated by `make model`. DO NOT EDIT.
// This file contains generated code based on the model.User struct.

package client

type User struct {
	Id       string `json:"id"`
	Username string `json:"username"`
}
